export const LOAD_COLOR = 'LOAD_COLOR'
export const LOAD_COLOR_SUCCESS = 'LOAD_COLOR'

export const LOAD_PATTERN = 'LOAD_PATTERN'
export const LOAD_PATTERN_SUCCESS = 'LOAD_COLOR'

export const GENERATE_RANDOM_COLOR = 'LOAD_RANDOM_COLOR'

export const SPAWN_SQUARE = 'SPAWN_SQUARE'
export const SPAWN_CIRCLE = 'SPAWN_SQUARE'
