export const LOAD_COLOR = 'LOAD_COLOR'
export const LOAD_COLOR_SUCCESS = 'LOAD_COLOR'

export const LOAD_PATTERN = 'LOAD_PATTERN'
export const LOAD_PATTERN_SUCCESS = 'LOAD_COLOR'

export const GENERATE_RANDOM_COLOR = 'LOAD_RANDOM_COLOR'

export const SPAWN_SQUARE = 'SPAWN_SQUARE'
export const SPAWN_SQUARE_SUCCESS = 'SPAWN_SQUARE_SUCCESS'
export const SPAWN_CIRCLE = 'SPAWN_CIRCLE'
export const SPAWN_CIRCLE_SUCCESS = 'SPAWN_CIRCLE_SUCCESS'
export const SPAWN_TRIANGLE = 'SPAWN_TRIANGLE'
export const SPAWN_TRIANGLE_SUCCESS = 'SPAWN_CIRCLE_SUCCESS'
export const SPAWN_RANDOM = 'SPAWN_TRIANGLE'

export const REMOVE_SHAPES = 'REMOVE_SHAPES'