

export const SPAWN_SHAPE = 'SPAWN_SHAPE'
export const SPAWN_SHAPE_SUCCESS = 'SPAWN_SHAPE_SUCCESS'
export const REMOVE_SHAPES = 'REMOVE_SHAPES'

export const CHANGE_SHAPE_BACKGROUND = 'CHANGE_SHAPE_BACKGROUND'
export const CHANGE_SHAPE_BACKGROUND_DONE = 'CHANGE_SHAPE_BACKGROUND_DONE'